# Generated by Django 6.0.7 on 2026-07-14 18:05

import django.core.validators
import orders.models.common
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.common.generate_random_code, editable=False, max_length=12, unique=True)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CA', 'Cash'), ('VS', 'Visa'), ('WT', 'Wallet'), ('FP', 'Fawry_pay')], default='CA', max_length=2)),
                ('payment_status', models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('FA', 'Failed')], default='PE', max_length=2)),
                ('shipping_name', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_street', models.CharField(max_length=200)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Preparing'), ('SH', 'Shipped'), ('DE', 'Delivered')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('product_name', models.CharField(max_length=100)),
                ('product_final_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=orders.models.common.generate_random_code, editable=False, max_length=12, unique=True)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
